USE RADISSONBLU_DB._HOTEL;

-- Create Table BRONZE_HOTEL_BOOKING
CREATE OR REPLACE TABLE BRONZE_HOTEL_BOOKING (
    BOOKING_ID                  VARCHAR(300),
    HOTEL_NAME                  VARCHAR(255),
    HOTEL_CITY                  VARCHAR(100),
    HOTEL_STATE                 VARCHAR(100),
    HOTEL_ZIPCODE               VARCHAR(20),
    HOTEL_COUNTRY               VARCHAR(100),
    BOOKING_FOR                 VARCHAR(50),
    NUMBERS_OF_PERSONS          NUMBER(5,0),
    ADULTS                      NUMBER(5,0),
    CHILDRENS                   NUMBER(5,0),
    DAYS_OF_STAYS               NUMBER(5,0),
    CHECK_IN_TIMESTAMP          TIMESTAMP_NTZ,
    CHECK_OUT_TIMESTAMP         TIMESTAMP_NTZ,
    REQUIRES_TRAVELS_FACILITY   VARCHAR(10),
    MODE_OF_TRAVELS             VARCHAR(100),
    AMOUNT                      NUMBER(18,2),
    DISCOUNT_CATEGORY           VARCHAR(100),
    SPECIAL_DISCOUNT            NUMBER(18,2),
    TAX                         NUMBER(18,2),
    TOTAL_AMOUNTS               NUMBER(18,2),
    ROOMS_BOOKED                NUMBER(5,0),
    ROOM_TYPE                   VARCHAR(100),
    BOOKING_SOURCE              VARCHAR(100),
    PAYMENT_METHOD              VARCHAR(50),
    GUEST_EMAIL                 VARCHAR(255),
    BOOKING_STATUS              VARCHAR(50),
    ROOM_NUMBER                 VARCHAR(20),
    GUEST_TYPE                  VARCHAR(50),
    GUEST_AGE                   NUMBER(5,0),
    GUEST_GENDER                VARCHAR(20)
);

-- Loading Data from Stage to Temp Table
CREATE TEMPORARY TABLE BRONZE_HOTEL_BOOKING_TMP LIKE BRONZE_HOTEL_BOOKING;

COPY INTO BRONZE_HOTEL_BOOKING_TMP
FROM @STG_HOTEL_BOOKING
FILE_FORMAT = (FORMAT_NAME = _hotel_booking_csv)
ON_ERROR = 'CONTINUE';

-- Insert into Bronze with BOOKING_ID lowercased
INSERT INTO BRONZE_HOTEL_BOOKING
SELECT
    LOWER(BOOKING_ID),
    HOTEL_NAME, HOTEL_CITY, HOTEL_STATE, HOTEL_ZIPCODE, HOTEL_COUNTRY,
    BOOKING_FOR, NUMBERS_OF_PERSONS, ADULTS, CHILDRENS,
    DAYS_OF_STAYS, CHECK_IN_TIMESTAMP, CHECK_OUT_TIMESTAMP,
    REQUIRES_TRAVELS_FACILITY, MODE_OF_TRAVELS,
    AMOUNT, DISCOUNT_CATEGORY, SPECIAL_DISCOUNT, TAX, TOTAL_AMOUNTS,
    ROOMS_BOOKED, ROOM_TYPE, BOOKING_SOURCE,
    PAYMENT_METHOD, GUEST_EMAIL, BOOKING_STATUS,
    ROOM_NUMBER, GUEST_TYPE, GUEST_AGE, GUEST_GENDER
FROM BRONZE_HOTEL_BOOKING_TMP;

DROP TABLE BRONZE_HOTEL_BOOKING_TMP;

-- Check whether it data is loaded or not
SELECT * FROM BRONZE_HOTEL_BOOKING LIMIT 20;