-- ============================================================
-- GOLD STATE 1
-- Regular Guests -> Confirmed Bookings -> Total Spend > $10,000
-- Purpose:
-- Identify high-value Regular guests for VIP conversion offers
-- ============================================================
USE DATABASE RADISSONBLU_DB;
USE SCHEMA _HOTEL;

SELECT * FROM SILVER_HOTEL_BOOKING;

-- ============================================================
-- 1. CREATE GOLD TABLE
-- ============================================================

CREATE OR REPLACE TABLE GOLD_REGULAR_GUEST_VIP_OFFER (
    
    GUEST_EMAIL              VARCHAR(255),
    GUEST_TYPE               VARCHAR(50),
    BOOKING_STATUS           VARCHAR(50),
    
    TOTAL_BOOKINGS           NUMBER(10,0),
    TOTAL_AMOUNT_SPENT       NUMBER(18,2),
    AVERAGE_BOOKING_VALUE   NUMBER(18,2),
    
    FIRST_BOOKING_DATE       DATE,
    LAST_BOOKING_DATE        DATE,
    
    VIP_OFFER_ELIGIBLE       VARCHAR(10),
    OFFER_TYPE               VARCHAR(100),
    
    CREATED_AT               TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


-- ============================================================
-- 2. INSERT ELIGIBLE REGULAR GUESTS
--
-- Conditions:
--   1. Guest Type = Regular
--   2. Booking Status = Confirmed
--   3. Total spending > 10,000 USD
--   4. Valid email
--   5. Activity considered within one year
-- ============================================================

INSERT INTO GOLD_REGULAR_GUEST_VIP_OFFER
(
    GUEST_EMAIL,
    GUEST_TYPE,
    BOOKING_STATUS,
    TOTAL_BOOKINGS,
    TOTAL_AMOUNT_SPENT,
    AVERAGE_BOOKING_VALUE,
    FIRST_BOOKING_DATE,
    LAST_BOOKING_DATE,
    VIP_OFFER_ELIGIBLE,
    OFFER_TYPE
)

SELECT

    LOWER(TRIM(GUEST_EMAIL)) AS GUEST_EMAIL,

    'Regular' AS GUEST_TYPE,

    'Confirmed' AS BOOKING_STATUS,

    COUNT(*) AS TOTAL_BOOKINGS,

    SUM(TOTAL_AMOUNTS) AS TOTAL_AMOUNT_SPENT,

    ROUND(
        AVG(TOTAL_AMOUNTS),
        2
    ) AS AVERAGE_BOOKING_VALUE,

    MIN(
        CAST(CHECK_IN_TIMESTAMP AS DATE)
    ) AS FIRST_BOOKING_DATE,

    MAX(
        CAST(CHECK_IN_TIMESTAMP AS DATE)
    ) AS LAST_BOOKING_DATE,

    'YES' AS VIP_OFFER_ELIGIBLE,

    'Radisson Blu VIP Upgrade Special Offer'
        AS OFFER_TYPE

FROM SILVER_HOTEL_BOOKING

WHERE
    UPPER(TRIM(GUEST_TYPE)) = 'REGULAR'

    AND UPPER(TRIM(BOOKING_STATUS)) = 'CONFIRMED'

    AND GUEST_EMAIL IS NOT NULL

    AND TRIM(GUEST_EMAIL) <> ''

    -- One-year window
    AND CHECK_IN_TIMESTAMP >= DATEADD(
        YEAR,
        -1,
        CURRENT_TIMESTAMP()
    )

GROUP BY
    LOWER(TRIM(GUEST_EMAIL)),
    GUEST_TYPE,
    BOOKING_STATUS

HAVING
    SUM(TOTAL_AMOUNTS) > 1000;


-- ============================================================
-- 3. VERIFY GOLD DATA
-- ============================================================

SELECT *
FROM GOLD_REGULAR_GUEST_VIP_OFFER
ORDER BY TOTAL_AMOUNT_SPENT DESC;


-- ============================================================
-- 4. NUMBER OF VIP-OFFER ELIGIBLE GUESTS
-- ============================================================

SELECT
    COUNT(*) AS VIP_OFFER_ELIGIBLE_GUESTS
FROM GOLD_REGULAR_GUEST_VIP_OFFER;


-- ============================================================
-- 5. TOTAL REVENUE GENERATED BY THESE GUESTS
-- ============================================================

SELECT
    SUM(TOTAL_AMOUNT_SPENT) AS TOTAL_REVENUE_FROM_ELIGIBLE_GUESTS
FROM GOLD_REGULAR_GUEST_VIP_OFFER;


-- ============================================================
-- 6. TOP 20 HIGH-VALUE REGULAR GUESTS
-- ============================================================

SELECT
    GUEST_EMAIL,
    TOTAL_BOOKINGS,
    TOTAL_AMOUNT_SPENT,
    AVERAGE_BOOKING_VALUE,
    FIRST_BOOKING_DATE,
    LAST_BOOKING_DATE
FROM GOLD_REGULAR_GUEST_VIP_OFFER
ORDER BY TOTAL_AMOUNT_SPENT DESC
LIMIT 20;
